### ISSUE TITLE
Warning: Error in as.character.factor: attempting to coerce non-factor

### ISSUE THREAD

**Issue by tklammsteiner** [EESI/themetagenomics#11]
Hello,

I tried to work through the "Finding Thematic Structure in the David Dataset" tutorial and simultaneously tested the workflow on my own data. The following error messages and issues all occured when using the David data and the [thematic structure](https://cran.r-project.org/web/packages/themetagenomics/vignettes/thematic_structure.html) tutorial. I was using 
```{r}
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)
```
Once I arrived at the visualization step...

```{r}
vis(TOPIC_EFFECTS, type = 'taxa')
```
...I got a couple of error messages when the plotly window containing the figures opened:

```{r}
Listening on http://127.0.0.1:6823
Warning: Error in as.character.factor: attempting to coerce non-factor
  [No stack trace available]
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
Warning: Error in as.character.factor: attempting to coerce non-factor
  101: <Anonymous>
Warning: The 'plotly_click' event tied a source ID of 'ord_click' is not registered. In order to obtain this event data, please add `event_register(p, 'plotly_click')` to the plot (`p`) that you wish to obtain event data from.
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
```
In addition there were several error messages within the plotly window ("Error: attempting to coerce non-factor") and only the plot showing the barchart was visible. If I tried to visualize the date with e.g. "type = continuous" or one of the two other options, even the bar chart did not appear as a plot.
I retried the analysis several times (e.g. after additionally installing the suggested packages,  using the dev version of the themetagenomics package, etc.)
The same goes for the visualization of functions with the command:
```{r}
vis(FUNCTION_EFFECTS2,TOPIC_EFFECTS,ui_level=.95)
```
Again similar errors in the console:
```{r}
Listening on http://127.0.0.1:6823
Warning: Error in as.character.factor: attempting to coerce non-factor
  [No stack trace available]
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
Warning: The 'plotly_click' event tied a source ID of 'hm_fxn' is not registered. In order to obtain this event data, please add `event_register(p, 'plotly_click')` to the plot (`p`) that you wish to obtain event data from.
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
Warning: Error in as.character.factor: attempting to coerce non-factor
  [No stack trace available]
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
Warning: Error in as.character.factor: attempting to coerce non-factor
  106: <Anonymous>
Warning: Error in proxy::dist: Can only handle data frames, vectors, matrices, and lists!
  [No stack trace available]
```
I researched the error messages and it seems that it has to do with some deeper problem in R when transforming S3 elements to S4, but my knowledge of R is not sufficient to provide solutions for that.

**Did anybody else experience a similar issue?** 
**Would be glad if somebody could help!**

**Comment by sw1** [comment]
Sorry. I had to make an update for the upcoming R v4.0. It was a simple update but apparently broke the vis functions. I have since fixed it and it seems to be working again. I am resubmitting to CRAN but it might take a few days. In the meantime, you can try devtools::install_github('sw1/themetagenomics',build_vignettes=TRUE).

**Comment by tklammsteiner** [comment]
Hey, thanks for the quick reply! Great to hear that the issue has already been fixed.

I tried to install the package via the command you posted:
```{r}
devtools::install_github('sw1/themetagenomics',build_vignettes=TRUE)
```
but unfortunately that did not work for me and the installation was terminated with some errors:
```{r}
Error: (converted from warning) Paket 'Rcpp' was built under R Version 3.6.3
Execution stopped
ERROR: lazy loading failed for package 'themetagenomics'
* removing '.../R/win-library/3.6/themetagenomics'
* restoring previous '.../R/win-library/3.6/themetagenomics'
Error: Failed to install 'themetagenomics' from GitHub:
  (converted from warning) installation of package ‘.../AppData/Local/Temp/RtmpcTV4km/file10446a496e04/themetagenomics_1.0.2.tar.gz’ had non-zero exit status
```
I checked again if all the package versions etc. are up to date, but that did not change anything.
So I will probably wait for the CRAN release and hope that I can get it to work

**Comment by tklammsteiner** [comment]
After installing the updated version and running your test data everything seems to work! Thanks a lot!

**Comment by gailrosen** [comment]
Wonderful!  Thanks, Steve!

________________________________________
